---
title: "Functional_redundancy"
author: "Adam_Koziol"
date: "5/12/2022"
output: html_document
---

```{r include=FALSE}
rm(list = ls(all.names = TRUE))
gc()
setwd('~/Documents/GitHub/Plasticity_Exp_Repo//Functional_redundancy')
library(tidyverse)
library(ape)
library(pheatmap)
library(RColorBrewer)
library(cowplot)
library(viridis) 
library(grid)
library(wesanderson)
library(phytools)
library(adiv)
library(vegan)
library(nlme)
```
Load data
```{r}
CR_counts <- read.csv('../data/TPM_CR.csv', row.names = 1, header = T)

AS_counts <- read.csv('../data/AS_TPM.csv', row.names=1, header = T) %>%
  select(!contains('FAST'))

metadata <- read.csv('../data/metadata.csv', row.names = 1, header = T)

functions_as <- read.csv('../damma/outputsR/distilled_binary_compounts_bin_AS.csv', sep=',') %>%
  .[.$X %in% rownames(AS_counts),] %>%
  as_data_frame %>% 
  column_to_rownames('X')

functions_cr <- read.csv('../damma/outputsR/distilled_binary_compounts_bin_CR.csv', sep=',') %>%
  .[.$X %in% rownames(CR_counts),] %>% 
  as_data_frame %>% 
  column_to_rownames('X')

CR_bins <- rownames(CR_counts)
AS_bins <- rownames(AS_counts)

alpha_diversities <- read.csv('../hill_numbers/outputsR/diversity_table.csv', row.names=1) %>%
  unique

```
Create TDS objects
```{r}
functions_cr_use <- functions_cr %>% select_if(is.numeric)
gower_CR <- vegdist(functions_cr_use, 'gower')
CR <- uniqueness(t(CR_counts), dis = gower_CR, abundance = T)

functions_AS_use <- functions_as %>% select_if(is.numeric)
gower_AS <- vegdist(functions_AS_use, 'gower')
AS <- uniqueness(t(AS_counts), dis = gower_AS, abundance = T)

```
Extract functional redundancies (Rstar)
```{r}
AS_Rstar <- AS$red %>%
  as.data.frame %>%
  rownames_to_column('sample_id') %>%
  dplyr::select(c(sample_id, Rstar)) %>%
  left_join(metadata, by='sample_id')

CR_Rstar <- CR$red %>%
  as.data.frame %>%
  rownames_to_column('sample_id') %>%
  dplyr::select(c(sample_id, Rstar)) %>%
  left_join(metadata, by='sample_id')

Functional_redundancy <- rbind(AS_Rstar, CR_Rstar)
Functional_redundancy <- Functional_redundancy %>% 
  mutate(treatment = factor(treatment, levels = c('Day1', 'Acc', 'Heat', 'Cold', 'Diet')))

```

```{r}
ggplot(unique(Functional_redundancy), aes(x=treatment, y=Rstar)) +
  facet_wrap(~species, nrow = 1) +
  geom_boxplot(width=0.5, aes(fill=treatment),size=0.25) +
  geom_jitter(alpha=0.2, position = position_jitter(0.2), size=0.5) +
  scale_fill_manual(values=c('#9DADC9', '#9187B0', '#8C6896', '#FFBFB8', '#FFD2B8', '#FFECCF')) +
  theme(panel.background = element_blank(),
        strip.background = element_blank(),
        axis.ticks.x = element_blank(),
        axis.text.x = element_text(angle = 45))

ggsave('./figures/functional_redundancy.png', height = 3, width = 5)
ggsave('./figures/functional_redundancy.pdf', height = 3, width = 5)
```

Find the averages and stdevs
```{r}
summaries <- Functional_redundancy %>%
  group_by(species) %>%
  summarise_each(funs(mean(Rstar),sd(Rstar))) %>%
  select_at(c(1:2, 12))
```
Model functional redundancy and species diversity

```{r}
Functional_redundancy1 <- alpha_diversities %>%
  select(c(sample_id, diversity)) %>%
  left_join(Functional_redundancy, by = 'sample_id') %>%
  mutate(species = ifelse(species == 'AS', 'A. sylvaticus', 'C. russula'))

redundancy_relationship <- ggplot(Functional_redundancy1, aes(x=log(diversity), y=Rstar, colour=species)) +
  geom_point() +
  scale_colour_manual(values=c('#FFD524', '#5c7f9d')) +
  theme(panel.background = element_blank(),
        legend.text = element_text(face='italic',
                                   size=10),
        legend.title = element_text(face='bold',
                                    size=10.5),
        legend.background = element_blank(),
        axis.line = element_line(),
        legend.key = element_blank(),
        legend.position = 'bottom') +
  xlab('Microbial diversity (log)') +
  ylab('Functional redundancy (Rstar)') +
  guides(col=guide_legend('Species'))

redundancy_relationship

ggsave('./figures/redundancy_relationship.png', redundancy_relationship, height = 3, width = 5)
ggsave('./figures/redundancy_relationship.pdf', redundancy_relationship, height = 3, width = 5)
ggsave('./figures/redundancy_relationship.tiff', compression = 'lzw', redundancy_relationship, height = 3, width = 5)
```
Tests of differences in funcional redundancy between species
```{r}
ks.test(Functional_redundancy$Rstar ~ Functional_redundancy$species, data=Functional_redundancy)
```


```{r eval=FALSE, include=FALSE}
# create multiple linear model
model_CR <- model_redundancy %>%
  filter(species == 'CR')

lm_fit <- lm(Rstar ~ log(q1), data=model_CR)
summary(lm_fit)

predicted_df <- data.frame(redun_predict = predict(lm_fit, model_CR), q1=model_CR$q1)

CR_model <- ggplot(model_CR,aes(x=log(q1), y=Rstar)) + 
  geom_point(color='blue') +
  geom_line(color='red',data = predicted_df, aes(x=log(q1), y=redun_predict))  +
  xlab('log microbial diversity') +
  ylab('Functional redundancy (Rstar)')
CR_model
```

```{r eval=FALSE, include=FALSE}
model_AS <- model_redundancy %>%
  filter(species == 'AS')

lm_fit <- lm(Rstar ~ log(q1), data=model_AS)
summary(lm_fit)

predicted_df <- data.frame(redun_predict = predict(lm_fit, model_AS), q1=model_AS$q1)

AS_model <- ggplot(model_AS,aes(x=log(q1), y=Rstar)) + 
  geom_point(color='blue') +
  geom_line(color='red',data = predicted_df, aes(x=log(q1), y=redun_predict)) +
  xlab('log microbial diversity') +
  ylab('Functional redundancy (Rstar)')

AS_model
```

```{r eval=FALSE, include=FALSE}
my_models <- ggpubr::ggarrange(AS_model,
                               CR_model,
                               labels = c('A', 'B'))
my_models

ggsave('./figures/redundancymodels.png', my_models, height = 7, width = 10)
```



```{r eval=FALSE, include=FALSE}
###Try to include the other factors 
model_redun.a <- lme(Rstar ~ q1 * species * sex,
                  random = ~1|cage/individual_id,
                  data = model_redundancy)
model_redun.b <- lme(Rstar ~ q1 * species + sex,
                  random = ~1|cage/individual_id,
                  data = model_redundancy)
model_redun.c <- lme(Rstar ~ q1 + species + sex,
                  random = ~1|cage/individual_id,
                  data = model_redundancy)
model_redun.d <- lme(log(Rstar) ~ q1 * species * sex,
                  random = ~1|cage/individual_id,
                  data = model_redundancy)
model_redun.e <- lme(log(Rstar) ~ q1 * species + sex,
                  random = ~1|cage/individual_id,
                  data = model_redundancy)
model_redun.f <- lme(log(Rstar) ~ q1 + species + sex,
                  random = ~1|cage/individual_id,
                  data = model_redundancy)



AIC(model_redun.a)
AIC(model_redun.b)
AIC(model_redun.c)
AIC(model_redun.d)
AIC(model_redun.e)
AIC(model_redun.f)
```

```{r eval=FALSE, include=FALSE}
model_redun=model_redun.d
E <- resid(model_redun, type = "normalized")
Fit <- fitted(model_redun)
op <- par(mfrow = c(1, 2))
plot(x = Fit, y = E,
     xlab = "Fitted values", ylab = "Residuals",
     main = "Residuals versus fitted values")
hist(E, nclreduns = 15)
```
```{r eval=FALSE, include=FALSE}
summary(model_redun.d)
```
```{r}
anova(model_redun.d)
```







