---
title: "damma for crocidura and apodemus"
author: "Adam_Koziol"
date: '2022-06-20'
output: html_document
---
set up script
```{r include=FALSE}
setwd('~/Documents/GitHub/Metgen_plasticityanalysis/distillR/')
library(distillR)
library(tidyverse)
library(data.table)
library(RColorBrewer)
```

Load data
```{r include=FALSE}
taxa <- read.csv('../data/taxa.csv', sep=',', header=T, row.names=1)

counts_CR <- read.csv('../data/TPM_CR.csv', row.names=1)

annotations_file="../data/annotations_cr.tsv"
annotations <- fread(annotations_file)
crocidura_completeness <- read.csv('/home/adam/Documents/GitHub/Plasticity_experiment_AS-CR/data/crocidura_binquality.csv', row.names = 1)
```

Re-do the pathway_db by changing the indole group function
```{r}
pathway_db_edit <- pathway_db %>% 
  mutate(Function = str_replace(Function, 'Indolic compound biosynthesis', 'Aromatic compound biosynthesis'),
         Code_function = str_replace(Code_function, 'B05', 'B08')) 
```

```{r include=FALSE}
MCIs <- distill(annotations,pathway_db_edit,genomecol=2,keggcol=9,eccol=c(10,19),pepcol=12)

#truncate bins into into the experimentally relevant bins
crocidura_completeness <- crocidura_completeness[rownames(crocidura_completeness) %in% rownames(counts_CR),]
#truncate the MCIs bins by the experimentally relevant bins
MCIs_real <- MCIs[rownames(MCIs) %in% rownames(counts_CR),]

#order the table into the same order
crocidura_completeness <- crocidura_completeness[match(rownames(MCIs_real),rownames(crocidura_completeness)),] %>%
  rownames_to_column('magnames') %>%
  select_at(-3)

write.csv(MCIs_real, '../distillR/outputsR/distilled_nonbinary_CR.csv')
```

Crocidura convert into compounds
```{r include=FALSE}
MCI_compounds <- distill_compounds(MCIs_real,pathway_db_edit)
write.csv(MCI_compounds, '../distillR/outputsR/distilled_nonbinary_compounds_CR.csv')
```

Crocidura convert into functions
```{r include=FALSE}
MCI_functions <- distill_functions(MCI_compounds,pathway_db_edit)
write.csv(MCI_functions, '../distillR/outputsR/distilled_table_functions_CR.csv')
```

Visualize heatmap
```{r}
#Prepare input table
compounds_table_df <- melt(MCI_compounds)
colnames(compounds_table_df) <- c("MAGs","Code_compound","Fullness")
compounds_table_df2 <- left_join(compounds_table_df, pathway_db_edit, by = 'Code_compound')
compounds_table_df2$Function <- as.factor(compounds_table_df2$Function)

#Plot heatmap
CR_plot <- ggplot(compounds_table_df2, aes(x=MAGs, y=Code_compound, fill=Fullness, group=Function))+
  geom_tile(colour="white", size=0.1)+
  scale_y_discrete(guide = guide_axis(check.overlap = TRUE))+
  scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+
  scale_fill_gradientn(limits = c(0,1), colours=brewer.pal(7, "YlGnBu"))+
  facet_grid(Function ~ ., scales = "free", space = "free")+
  theme_grey(base_size=8)+
  theme(strip.text.y = element_text(angle = 0,
                                    size = 12),axis.text.x=element_blank(),
        axis.title.y = element_text(size = 10),
        axis.title = element_text(face='italic')) +
  ggtitle('C. russula')

CR_plot
ggsave('../distillR/figure/Crocidura_magbyfuctions.png', height = 15, width = 10)
```



```{r include=FALSE}
annotations_file_apo="../data/annotations.tsv"
annotations_apo <- fread(annotations_file_apo)
counts_AS <- read.csv('../data/AS_TPM.csv', row.names = 1)


apodemus_completeness <- read.csv('../data/apodemus_binquality.csv', sep='\t') %>%
  select(c('Bin.Id', 'Completeness', 'Contamination')) %>%
  mutate(Bin.Id = str_c('bin_', Bin.Id)) %>% 
  column_to_rownames('Bin.Id')

MCIs_apo <- distill(annotations_apo,pathway_db_edit,genomecol=2,keggcol=9,eccol=c(10,19),pepcol=12)

#truncate bins into into the experimentally relevant bins
apodemus_completeness <- apodemus_completeness[rownames(apodemus_completeness) %in% rownames(counts_AS),] %>%
  as.data.frame
#truncate the MCIs bins by the experimentally relevant bins
MCIs_real_apo <- MCIs_apo[rownames(MCIs_apo) %in% rownames(counts_AS),]

#order the table into the same order
apodemus_completeness <- apodemus_completeness[match(rownames(MCIs_real_apo),rownames(apodemus_completeness)),] %>%
  rownames_to_column('magnames') %>%
  select_at(-3)

write.csv(MCIs_real_apo, './outputsR/distilled_nonbinary_AS.csv')
```


Apodemus convert into compounds
```{r include=FALSE}
MCI_compounds_apo <- distill_compounds(MCIs_real_apo,pathway_db_edit)
write.csv(MCI_compounds_apo, '../distillR/outputsR/distilled_nonbinary_compounds_AS.csv')
```

Apodemus convert into functions
```{r include=FALSE}
MCI_functions_apo <- distill_functions(MCI_compounds_apo,pathway_db_edit)
write.csv(MCI_functions_apo, '../distillR/outputsR/distilled_table_functions_AS.csv')
```
Indexing the functions by classification
```{r}
#Prepare input table
compounds_table_df <- melt(MCI_compounds_apo)
colnames(compounds_table_df) <- c("MAGs","Code_compound","Fullness")
compounds_table_df2 <- merge(compounds_table_df,pathway_db_edit,by.x="Code_compound",by.y="Code_compound")
compounds_table_df2$Function <- as.factor(compounds_table_df2$Function)

#Plot heatmap
ggplot(compounds_table_df2, aes(x=MAGs, y=Code_compound, fill=Fullness, group=Function))+
  geom_tile(colour="white", size=0.1)+
  scale_y_discrete(guide = guide_axis(check.overlap = TRUE))+
  scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+
  scale_fill_gradientn(limits = c(0,1), colours=brewer.pal(7, "YlGnBu"))+
  facet_grid(Function ~ ., scales = "free", space = "free")+
  theme_grey(base_size=8)+
  theme(strip.text.y = element_text(angle = 0),axis.text.x=element_blank())
ggsave('./figure/Apodemus_magbyfuctions.png', height = 15, width = 10)
```

Increaser vs decreaser heatmaps for Crocidura russula
```{r eval=FALSE, include=FALSE}
increasers <- c("bin_s6.mtb27",
                "bin_s36.vmb0",
                "bin_s21.mxb8",
                "bin_s14.cct6",
                "bin_s13.vmb19",
                "bin_s36.mxb13",
                "bin_s34.cct50",
                "bin_s13.cct72",
                "bin_s6.vmb19",
                "bin_s27.mtb32",
                "bin_s13.vmb53",
                "bin_s14.cct55_sub",
                "bin_s27.vmb32")

decreasers <- c("bin_s28.mxb31",
                "bin_s19.cct18_sub",
                "bin_s14.mtb52",
                "bin_s19.vmb3",
                "bin_s28.mtb8",
                "bin_s23.cct42",
                "bin_s36.mtb18",
                "bin_s34.mtb22_sub",
                "bin_s14.mtb51",
                "bin_s14.vmb0",
                "bin_s4.vmb27",
                "bin_s34.cct27",
                "bin_s21.mxb1",
                "bin_s2.mxb1",
                "bin_s35.cct57_sub",
                "bin_s27.mtb39")

bidirection <- c("bin_s6.mtb27",
                "bin_s36.vmb0",
                "bin_s21.mxb8",
                "bin_s14.cct6",
                "bin_s13.vmb19",
                "bin_s36.mxb13",
                "bin_s34.cct50",
                "bin_s13.cct72",
                "bin_s6.vmb19",
                "bin_s27.mtb32",
                "bin_s13.vmb53",
                "bin_s14.cct55_sub",
                "bin_s27.vmb32",
                "bin_s28.mxb31",
                "bin_s19.cct18_sub",
                "bin_s14.mtb52",
                "bin_s19.vmb3",
                "bin_s28.mtb8",
                "bin_s23.cct42",
                "bin_s36.mtb18",
                "bin_s34.mtb22_sub",
                "bin_s14.mtb51",
                "bin_s14.vmb0",
                "bin_s4.vmb27",
                "bin_s34.cct27",
                "bin_s21.mxb1",
                "bin_s2.mxb1",
                "bin_s35.cct57_sub",
                "bin_s27.mtb39")

annotation_row <- bidirection %>%
  as.data.frame %>%
  rename('MAG' = '.') %>%
  mutate(Direction = ifelse(MAG %in% increasers, 'Increasers', 'Decreasers')) %>%
  left_join(taxa[,c(1,3)], by = c('MAG'='user_genome')) %>%
  mutate(Phylum = str_remove_all(Phylum, '_A$')) %>%
  column_to_rownames('MAG')

distilled_increasers <- cr_zscores %>%
  .[bidirection,]

heatmap <- pheatmap(distilled_increasers,
           fontsize_row = 12,
           cluster_cols = F,
           annotation_row = annotation_row,
           fontsize_col = 12,
           angle_col = 45,
           cluster_rows = F,
           cutree_rows = 2,
           gaps_row = 13)
ggsave('./figure/direction_heatmap.png', heatmap, width = 10, height = 7)
ggsave('./figure/direction_heatmap.pdf', heatmap, width = 10, height = 7)

```

sample plot in damma 
```{r eval=FALSE, include=FALSE}
#Prepare input table
compounds_table_df <- distilled_table_functions %>%
  .[bidirection,] %>%
  rownames_to_column('MAGs') %>% 
  melt(.)
colnames(compounds_table_df) <- c("MAGs","Compounds","Fullness")
#Plot heatmap
ggplot(compounds_table_df, aes(x=MAGs, y=Compounds, fill=Fullness))+
  geom_tile(colour="white", size=0.1)+
  facet_grid(~annotation_row$Direction, scales = 'free') +
  scale_y_discrete(guide = guide_axis(check.overlap = TRUE))+
  scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+
  scale_fill_gradientn(limits = c(0,1), colours = rev(c("#781a25","#d53e4f", "#f46d43", "#fdae61", "#fee08b", "#e6f598", "#abdda4", "#ddf1da","#f1faf0","#f4f4f4")))+
  scale_fill_gradientn(limits = c(0,1), colours=brewer.pal(7, "YlGnBu"))+
  theme_grey(base_size=8)+
  theme_bw() +
  theme(strip.text.y = element_text(angle = 0),
        strip.background = element_blank(),
        strip.text = element_text(size = 12,
                                  face='bold'),
        axis.text.y = element_text(size = 10),
        axis.text.x = element_blank())
  
        
ggsave('./figure/Crocidura_increaser_decreasers.png', height = 7, width = 10)
```


