---
title: "Beta_diversity_linearmodels"
author: "Adam_Koziol"
date: "4/22/2022"
output:
  html_document: default
  pdf_document: default
---

```{r include=FALSE}
setwd('~/Documents/GitHub/Metgen_plasticityanalysis/linear_models')
library(tidyverse)
library(nlme)
library(grid)
library(janitor)
library(broom)
library(ggplotify)
library(multcomp)
library(tinytex)
`%!in%` = Negate(`%in%`)
```

```{r}
####Load the metadata
metadata_combined <- read.csv('../data/metadata.csv') %>%
  dplyr::select(c(sample_id, individual_id, cage, sex)) %>%
  unique
```


```{r}
#####Beta diversity containing taxonomic diversities
beta_diversity_tax_as <- read.csv('../hill_numbers/outputsR/dissimilarity_combined_td.csv', header=T, row.names = 1) %>%
  filter(Species == 'AS') %>% 
  dplyr::select(c(Treatment_pair, beta, individual_id, treatmentWspecies, Species)) %>% 
  mutate(Treatment_pair = str_remove_all(Treatment_pair, '[1]$'),
         days=case_when(Treatment_pair == 'Day_Acc' ~ 7,
                        Treatment_pair == 'Acc_Heat' ~ 19,
                        Treatment_pair == 'Heat_Cold' ~ 33,
                        Treatment_pair == 'Cold_Diet' ~ 45),
         Treatment_pair=factor(Treatment_pair, levels = c("Day_Acc","Acc_Heat","Heat_Cold","Cold_Diet"))) %>%
  left_join(metadata_combined[,c('individual_id', 'cage', 'sex')], by = 'individual_id') %>% 
  unique

beta_diversity_tax_cr <- read.csv('../hill_numbers/outputsR/dissimilarity_combined_td.csv', header=T, row.names = 1) %>%
  filter(Species == 'CR') %>% 
  dplyr::select(c(Treatment_pair, beta, individual_id, treatmentWspecies, Species)) %>% 
  mutate(Treatment_pair = str_remove_all(Treatment_pair, '[1]$'),
         days=case_when(Treatment_pair == 'Day_Acc' ~ 7,
                        Treatment_pair == 'Acc_Heat' ~ 19,
                        Treatment_pair == 'Heat_Cold' ~ 33,
                        Treatment_pair == 'Cold_Diet' ~ 45),
         Treatment_pair=factor(Treatment_pair, levels = c("Day_Acc","Acc_Heat","Heat_Cold","Cold_Diet"))) %>%
  left_join(metadata_combined[,c('individual_id', 'cage', 'sex')], by = 'individual_id') %>% 
  unique
```


```{r}
#####Beta diversity containing functional diveristies Apodemus
beta_div_fd_as <- read.csv('../hill_numbers/outputsR/dissimilarity_combined_fd.csv', header=T) %>%
  filter(Species == 'AS') %>%
  dplyr::select(c(Treatment_pair, beta, individual_id, treatmentWspecies, Species)) %>% 
  mutate(Treatment_pair = str_remove_all(Treatment_pair, '[1]$'),
         days=case_when(Treatment_pair == 'Day_Acc' ~ 7,
                        Treatment_pair == 'Acc_Heat' ~ 19,
                        Treatment_pair == 'Heat_Cold' ~ 33,
                        Treatment_pair == 'Cold_Diet' ~ 45),
         Treatment_pair=factor(Treatment_pair, levels = c("Day_Acc","Acc_Heat","Heat_Cold","Cold_Diet"))) %>%
  left_join(metadata_combined[,c('individual_id', 'cage', 'sex')], by = 'individual_id') %>% 
  unique

######Beta diversity containing functional diversities Crocidura - There was a problem where FD values were incorrectly 
######Individuals without 4 samples are removed

beta_div_fd_cr <- read.csv('../hill_numbers/outputsR/dissimilarity_combined_fd.csv', header=T) %>%
  filter(Species == 'CR') %>%
  dplyr::select(c(Treatment_pair, beta, individual_id, treatmentWspecies, Species)) %>% 
  mutate(Treatment_pair = str_remove_all(Treatment_pair, '[1]$'),
         days=case_when(Treatment_pair == 'Day_Acc' ~ 7,
                        Treatment_pair == 'Acc_Heat' ~ 19,
                        Treatment_pair == 'Heat_Cold' ~ 33,
                        Treatment_pair == 'Cold_Diet' ~ 45),
         Treatment_pair=factor(Treatment_pair, levels = c("Day_Acc","Acc_Heat","Heat_Cold","Cold_Diet"))) %>%
  left_join(metadata_combined[,c('individual_id', 'cage', 'sex')], by = 'individual_id') %>% 
  unique
```


```{r}
#####Load in the phylogenetic beta-diversities
beta_div_pd_as <- read.csv('../hill_numbers/outputsR/Beta_combined_pd.csv', header=T) %>%
  filter(Species == 'AS') %>% 
  dplyr::select(c(Treatment_pair, beta, individual_id, treatmentWspecies, Species)) %>% 
  mutate(Treatment_pair = str_remove_all(Treatment_pair, '[1]$'),
         days=case_when(Treatment_pair == 'Day_Acc' ~ 7,
                        Treatment_pair == 'Acc_Heat' ~ 19,
                        Treatment_pair == 'Heat_Cold' ~ 33,
                        Treatment_pair == 'Cold_Diet' ~ 45),
         Treatment_pair=factor(Treatment_pair, levels = c("Day_Acc","Acc_Heat","Heat_Cold","Cold_Diet"))) %>%
  left_join(metadata_combined[,c('individual_id', 'cage', 'sex')], by = 'individual_id') %>% 
  unique

beta_div_pd_cr <- read.csv('../hill_numbers/outputsR/Beta_combined_pd.csv', header=T) %>%
  filter(Species == 'CR') %>% 
  dplyr::select(c(Treatment_pair, beta, individual_id, treatmentWspecies, Species)) %>% 
  mutate(Treatment_pair = str_remove_all(Treatment_pair, '[1]$'),
         days=case_when(Treatment_pair == 'Day_Acc' ~ 7,
                        Treatment_pair == 'Acc_Heat' ~ 19,
                        Treatment_pair == 'Heat_Cold' ~ 33,
                        Treatment_pair == 'Cold_Diet' ~ 45),
         Treatment_pair=factor(Treatment_pair, levels = c("Day_Acc","Acc_Heat","Heat_Cold","Cold_Diet"))) %>%
  left_join(metadata_combined[,c('individual_id', 'cage', 'sex')], by = 'individual_id') %>% 
  unique
```

Sanity check of each factor
```{r}
contr_as <- rbind("T1:T2" = c(1, -1, 0, 0),
               "T2:T3" = c(0, 1, -1, 0),
               "T3:T4" = c(0, 0, 1,-1))
contr_cr <- rbind("T1:T2" = c(1, -1, 0, 0),
               "T2:T3" = c(0, 1, -1, 0),
               "T3:T4" = c(0, 0, 1,-1))
               #"COLD-DIET" = c(0, 0, 0, 1,-1))
```

####Functional diversities
```{r}
boxplot(beta~Treatment_pair,data = beta_div_fd_as)
```

```{r}
boxplot(log1p(beta)~Treatment_pair,data = beta_div_fd_as)
```

```{r}
model_as.a_fd <- lme(beta~Treatment_pair,
                  random = ~1|cage/individual_id,
                  correlation = corCAR1(form = ~ as.numeric(days)),
                  data=beta_div_fd_as)
model_as.b_fd <- lme(beta~Treatment_pair,
                  random = ~1|individual_id,
                  correlation = corCAR1(form = ~ as.numeric(days)),
                  data=beta_div_fd_as)
model_as.c_fd <- lme(beta~Treatment_pair,
                  random = ~1|individual_id,
                  data=beta_div_fd_as)
model_as.d_fd <- lme(beta~Treatment_pair,
                  random = ~1|cage,
                  data=beta_div_fd_as)
model_as.e_fd <- lme(beta~Treatment_pair,
                  random = ~1|cage/individual_id,
                  data=beta_div_fd_as)
model_as.f_fd <- lm(beta~Treatment_pair,
                  data=beta_div_fd_as)
AIC(model_as.a_fd) 
AIC(model_as.b_fd) 
AIC(model_as.c_fd)
AIC(model_as.d_fd) 
AIC(model_as.e_fd)
AIC(model_as.f_fd)
```


```{r}
model_as1=model_as.a_fd
E <- resid(model_as1, type = "normalized")
Fit <- fitted(model_as1)
op <- par(mfrow = c(1, 2))
plot(x = Fit, y = E,
     xlab = "Fitted values", ylab = "Residuals",
     main = "Residuals versus fitted values")
hist(E, nclass = 15)
```

```{r}
par(op)
bp=boxplot(E ~ Treatment_pair,
           data = beta_div_fd_as)
```
```{r}
summary(model_as1)
```


```{r}
anova(model_as1)
```

```{r}
######No significant differences this can be excluded
beta_as_summary <- summary(glht(model_as.a_fd, mcp(Treatment_pair=contr_as),
                   test = adjusted("holm")))
beta_as_summary
```
######Functional Beta diversities Crocidura
```{r}
boxplot(beta~Treatment_pair,data = beta_div_fd_cr)
```

```{r}
boxplot(log(beta)~Treatment_pair,data = beta_div_fd_cr)
```

```{r}
model_cr.a_fd <- lme(beta~Treatment_pair,
                  random = ~1|cage/individual_id,
                  correlation = corCAR1(form = ~ days),
                  data=beta_div_fd_cr)
model_cr.b_fd <- lme(beta~Treatment_pair,
                  random = ~1|individual_id,
                  correlation = corCAR1(form = ~ days),
                  data=beta_div_fd_cr)
model_cr.c_fd <- lme(beta~Treatment_pair,
                  random = ~1|cage/individual_id,
                  data=beta_div_fd_cr)
model_cr.d_fd <- lme(beta~Treatment_pair,
                  random = ~1|cage,
                  data=beta_div_fd_cr)
model_cr.e_fd <- lme(beta~Treatment_pair,
                  random = ~1|cage/individual_id,
                  data=beta_div_fd_cr)
model_cr.f_fd <- lm(beta~Treatment_pair,
                  data=beta_div_fd_cr)
AIC(model_cr.a_fd) 
AIC(model_cr.b_fd) 
AIC(model_cr.c_fd) 
AIC(model_cr.d_fd) 
AIC(model_cr.e_fd)
AIC(model_cr.f_fd)
```


```{r}
model_cr1_fd=model_cr.a_fd
E <- resid(model_cr1_fd, type = "normalized")
Fit <- fitted(model_cr1_fd)
op <- par(mfrow = c(1, 2))
plot(x = Fit, y = E,
     xlab = "Fitted values", ylab = "Residuals",
     main = "Residuals versus fitted values")
hist(E, nclass = 15)
```

```{r}
par(op)
bp=boxplot(E ~ Treatment_pair,
           data = beta_div_fd_cr)
```
```{r}
summary(model_cr1_fd)
```


```{r}
anova(model_cr1_fd)
```

```{r}
beta_cr_summary_fd <- summary(glht(model_cr1_fd, linfct=mcp(Treatment_pair="Tukey")))
beta_cr_summary_fd
```
#####Beta diversity for taxonomic hill numbers
#####Apodemus

```{r}
boxplot(beta~Treatment_pair,data = beta_diversity_tax_as)
```

```{r}
boxplot(log(beta)~Treatment_pair,data = beta_diversity_tax_as)

```
```{r}
model_as.a <- lme(beta~Treatment_pair,
                  random = ~1|cage/individual_id,
                  correlation = corCAR1(form = ~as.numeric(days)),
                  data=beta_diversity_tax_as)
model_as.b <- lme(beta~Treatment_pair,
                  random = ~1|individual_id,
                  correlation = corCAR1(form = ~as.numeric(days)),
                  data=beta_diversity_tax_as)
model_as.c <- lme(beta~Treatment_pair,
                  random = ~1|cage/individual_id,
                  correlation = corCAR1(form = ~as.numeric(days)),
                  data=beta_diversity_tax_as)
model_as.d <- lme(beta~Treatment_pair,
                  random = ~1|cage,
                  data=beta_diversity_tax_as)
model_as.e <- lme(beta~Treatment_pair,
                  random = ~1|cage/individual_id,
                  data=beta_diversity_tax_as)
model_as.f <- lm(beta~Treatment_pair,
                  data=beta_diversity_tax_as)

AIC(model_as.a) #-57.31332
AIC(model_as.b) #-72.88434
AIC(model_as.c) #-75.6534
AIC(model_as.d) #-57.31332
AIC(model_as.e) #-72.88434
AIC(model_as.f) #-75.6534
```
```{r}
model_as1=model_as.a
E <- resid(model_as1, type = "normalized")
Fit <- fitted(model_as1)
op <- par(mfrow = c(1, 2))
plot(x = Fit, y = E,
     xlab = "Fitted values", ylab = "Residuals",
     main = "Residuals versus fitted values")
hist(E, nclass = 15)
```

```{r}
par(op)
bp=boxplot(E ~ Treatment_pair,
           data = beta_diversity_tax_as)
```

```{r}
anova(model_as.a)
```

```{r}
######No significant difference found, this can be excluded
beta_as_summary <- summary(glht(model_as.b, linfct=mcp(Treatment_pair="Tukey")))
beta_as_summary #####Reduction needed in the number of comparisons
```
Beta diversity Crocidura
```{r}
boxplot(beta~Treatment_pair,data = beta_diversity_tax_cr)
```

```{r}
boxplot(log(beta)~Treatment_pair,data = beta_diversity_tax_cr)
```

```{r}
model_cr.a <- lme(beta~Treatment_pair,
                  random = ~1|cage/individual_id,
                  correlation = corCAR1(form = ~days),
                  data=beta_diversity_tax_cr)
model_cr.b <- lme(beta~Treatment_pair,
                  random = ~1|individual_id,
                  correlation = corCAR1(form = ~days),
                  data=beta_diversity_tax_cr)
model_cr.c <- lme(beta~Treatment_pair,
                  random = ~1|cage/individual_id,
                  data=beta_diversity_tax_cr)
model_cr.d <- lme(beta~Treatment_pair,
                  random = ~1|cage/individual_id,
                  data=beta_diversity_tax_cr)
model_cr.e <- lme(beta~Treatment_pair,
                  random = ~1|cage,
                  data=beta_diversity_tax_cr)
model_cr.f <- lme(beta~Treatment_pair,
                  random = ~1|individual_id,
                  data=beta_diversity_tax_cr)
AIC(model_cr.a) 
AIC(model_cr.b) 
AIC(model_cr.c) 
AIC(model_cr.d)
AIC(model_cr.e)
AIC(model_cr.f)
```

```{r}
model_cr1=model_cr.a
E <- resid(model_cr1, type = "normalized")
Fit <- fitted(model_cr1)
op <- par(mfrow = c(1, 2))
plot(x = Fit, y = E,
     xlab = "Fitted values", ylab = "Residuals",
     main = "Residuals versus fitted values")
hist(E, nclass = 15)
```

```{r}
par(op)
bp=boxplot(E ~ Treatment_pair,
           data = beta_diversity_tax_cr)
```

```{r}
anova(model_cr.a)
```

```{r}
beta_cr_summary_fd <- summary(glht(model_cr.a, linfct=mcp(Treatment_pair="Tukey")))
beta_cr_summary_fd
```

```{r}
summary(model_cr.a)
```
Beta diversity Phylogenetic Apodemus
```{r}
boxplot(beta~Treatment_pair,data = beta_div_pd_as)
```

```{r}
model_as.pd.a <- lme(beta~Treatment_pair,
                  random = ~1|cage/individual_id,
                  data=beta_div_pd_as)
model_as.pd.b <- lme(beta~Treatment_pair,
                  random = ~1|individual_id,
                  correlation = corCAR1(form = ~days),
                  data=beta_div_pd_as)
model_as.pd.c <- lme(beta~Treatment_pair,
                  random = ~1|cage,
                  data=beta_div_pd_as)
model_as.pd.d <- lme(beta~Treatment_pair,
                  random = ~1|individual_id,
                  data=beta_div_pd_as)
model_as.pd.e <- lme(beta~Treatment_pair,
                  random = ~1|cage/individual_id,
                  data=beta_div_pd_as)
model_as.pd.f <- lm(beta~Treatment_pair,
                  random = ~1|cage,
                  data=beta_div_pd_as)
AIC(model_as.pd.a)
AIC(model_as.pd.b)
AIC(model_as.pd.c)
AIC(model_as.pd.d)
AIC(model_as.pd.e)
AIC(model_as.pd.f)
```

```{r}
model_as1=model_as.pd.a
E <- resid(model_as1, type = "normalized")
Fit <- fitted(model_as1)
op <- par(mfrow = c(1, 2))
plot(x = Fit, y = E,
     xlab = "Fitted values", ylab = "Residuals",
     main = "Residuals versus fitted values")
hist(E, nclass = 15)
```

```{r}
par(op)
bp=boxplot(E ~ Treatment_pair,
           data = beta_div_pd_as)
```

```{r}
anova(model_as1)
```


```{r}
summary(model_as1)
```
Phylogenetic Hill numbers CR
```{r}
boxplot(beta~Treatment_pair,data = beta_div_pd_cr)
```

```{r}
model_cr.pd.a <- lme(beta~Treatment_pair,
                  random = ~1|cage/individual_id,
                  data=beta_div_pd_cr)
model_cr.pd.b <- lme(beta~Treatment_pair,
                  random = ~1|individual_id,
                  correlation = corCAR1(form = ~days),
                  data=beta_div_pd_cr)
model_cr.pd.c <- lme(beta~Treatment_pair,
                  random = ~1|cage/individual_id,
                  data=beta_div_pd_cr)
model_cr.pd.d <- lme(beta~Treatment_pair,
                  random = ~1|cage,
                  data=beta_div_pd_cr)
model_cr.pd.e <- lme(beta~Treatment_pair,
                  random = ~1|individual_id,
                  data=beta_div_pd_cr)
model_cr.pd.f <- lm(beta~Treatment_pair,
                  data=beta_div_pd_cr)
AIC(model_cr.pd.a) #-31.32403
AIC(model_cr.pd.b) #-42.60456
AIC(model_cr.pd.c) #-45.66955
AIC(model_cr.pd.d) #-31.32403
AIC(model_cr.pd.e) #-42.60456
AIC(model_cr.pd.f) #-45.66955
```

```{r}
model_cr1=model_cr.pd.a
E <- resid(model_cr1, type = "normalized")
Fit <- fitted(model_cr1)
op <- par(mfrow = c(1, 2))
plot(x = Fit, y = E,
     xlab = "Fitted values", ylab = "Residuals",
     main = "Residuals versus fitted values")
hist(E, nclass = 15)
```

```{r}
par(op)
bp=boxplot(E ~ Treatment_pair,
           data = beta_div_pd_cr)
```

```{r}
anova(model_cr1)
```


```{r}
summary(model_cr1)
```

Overall beta-diversity comparison
```{r}
overall_beta_div <- read.csv('../hill_numbers/outputsR/total_betadiversity_td.csv', row.names = 1) %>%
  mutate(cage=case_when(species == 'CR' & cage == 1 ~ 6,
                        species == 'CR' & cage == 2 ~ 7,
                        species == 'CR' & cage == 3 ~ 8,
                        species == 'CR' & cage == 4 ~ 9,
                        species == 'CR' & cage == 5 ~ 10,
                        species == 'CR' & cage == 6 ~ 11,
                        TRUE ~ as.numeric(cage)))
```

```{r}
boxplot(beta.dissimilarity~species,data = overall_beta_div)
```

```{r}
model_beta_tax_combined <- lme(beta.dissimilarity~species,
                  random = ~1|cage,
                  data=overall_beta_div)
AIC(model_beta_tax_combined) #-31.32403
```

```{r}
E <- resid(model_beta_tax_combined, type = "normalized")
Fit <- fitted(model_beta_tax_combined)
op <- par(mfrow = c(1, 2))
plot(x = Fit, y = E,
     xlab = "Fitted values", ylab = "Residuals",
     main = "Residuals versus fitted values")
hist(E, nclass = 15)
```

```{r}
#par(op)
#bp=boxplot(E ~ species,
 #          data = model_beta_tax_combined)
```

```{r}
anova(model_beta_tax_combined)
```


```{r}
summary(model_beta_tax_combined)
```


```{r}
overall_beta_div_pd <- read.csv('../hill_numbers/outputsR/total_betadiversity_pd.csv', row.names = 1) %>%
  mutate(cage=case_when(species == 'CR' & cage == 1 ~ 6,
                        species == 'CR' & cage == 2 ~ 7,
                        species == 'CR' & cage == 3 ~ 8,
                        species == 'CR' & cage == 4 ~ 9,
                        species == 'CR' & cage == 5 ~ 10,
                        species == 'CR' & cage == 6 ~ 11,
                        TRUE ~ as.numeric(cage)))
```

```{r}
boxplot(beta.dissimilarity~species,data = overall_beta_div_pd)
```

```{r}
model_beta_pd_combined <- lme(beta.dissimilarity~species,
                  random = ~1|cage,
                  data=overall_beta_div_pd)
AIC(model_beta_pd_combined) #-31.32403
```

```{r}
E <- resid(model_beta_pd_combined, type = "normalized")
Fit <- fitted(model_beta_pd_combined)
op <- par(mfrow = c(1, 2))
plot(x = Fit, y = E,
     xlab = "Fitted values", ylab = "Residuals",
     main = "Residuals versus fitted values")
hist(E, nclass = 15)
```

```{r}
#par(op)
#bp=boxplot(E ~ species,
 #          data = model_beta_tax_combined)
```

```{r}
anova(model_beta_pd_combined)
```


```{r}
summary(model_beta_pd_combined)
```


```{r}
overall_beta_div_fd <- read.csv('../hill_numbers/outputsR/total_betadiversity_fd.csv', row.names = 1) %>%
  mutate(cage=case_when(species == 'CR' & cage == 1 ~ 6,
                        species == 'CR' & cage == 2 ~ 7,
                        species == 'CR' & cage == 3 ~ 8,
                        species == 'CR' & cage == 4 ~ 9,
                        species == 'CR' & cage == 5 ~ 10,
                        species == 'CR' & cage == 6 ~ 11,
                        TRUE ~ as.numeric(cage)))
```

```{r}
boxplot(beta.dissimilarity~species,data = overall_beta_div_fd)
```

```{r}
model_beta_fd_combined <- lme(beta.dissimilarity~species,
                  random = ~1|cage,
                  data=overall_beta_div_fd)
AIC(model_beta_fd_combined) #-31.32403
```

```{r}
E <- resid(model_beta_fd_combined, type = "normalized")
Fit <- fitted(model_beta_fd_combined)
op <- par(mfrow = c(1, 2))
plot(x = Fit, y = E,
     xlab = "Fitted values", ylab = "Residuals",
     main = "Residuals versus fitted values")
hist(E, nclass = 15)
```

```{r}
#par(op)
#bp=boxplot(E ~ species,
 #          data = model_beta_tax_combined)
```

```{r}
anova(model_beta_fd_combined)
```


```{r}
summary(model_beta_fd_combined)
```

```{r}
beta_tax <- rbind(beta_diversity_tax_cr, beta_diversity_tax_as) %>%
  group_by(Species) %>%
  dplyr::select(-c(cage, sex, individual_id, individual_id, Treatment_pair)) %>%
  dplyr::summarise_each(funs(mean,sd,se=sd(.)/sqrt(n())))

beta_fd <- rbind(beta_div_fd_cr, beta_div_fd_as) %>%
  group_by(Species) %>%
  dplyr::select(-c(cage, sex, individual_id, Treatment_pair)) %>%
  dplyr::summarise_each(funs(mean,sd,se=sd(.)/sqrt(n())))

beta_pd <- rbind(beta_div_pd_cr, beta_div_pd_as) %>%
  group_by(Species) %>%
  dplyr::select(-c(cage, sex, individual_id, Treatment_pair)) %>%
  dplyr::summarise_each(funs(mean,sd,se=sd(.)/sqrt(n())))
```

```{r}
sessioninfo::session_info()
```



